### ISSUE TITLE
Naming conventions

### ISSUE THREAD

**Issue by friedow** [bptlab/rembrandt#1]
## Conditions of Satisfaction
- [x] Everyone in the team is informed about the conventions.
- [x] The conventions are added to the rembrandt readme.

I personally like these naming conventions a lot: [naming conventions](https://github.com/basarat/typescript-book/blob/master/docs/styleguide/styleguide.md). The only thing I would add is that file naming should differ whether the exported object is a class or an instance.

## Filename

* Use `PascalCase` for classes
* Use `camelCase` for instances

> Reason: Default export for files is clear

### Class as default export

**Bad**
```ts
export default class HelloWorld {}

helloWorld.ts
```
**Good**
```ts
export default class HelloWorld {}

HelloWorld.ts
```

### Instance as default export

**Bad**
```ts
export default const helloWorld: string = 'Hello World!';

HelloWorld.ts
```
**Good**
```ts
export default const helloWorld: string = 'Hello World!';

helloWorld.ts
```

How do you think about that?

**Comment by MaximilianV** [comment]
👍
