### ISSUE TITLE
Find More Illustrative Use-Cases

### ISSUE THREAD

**Issue by MaximilianV** [bptlab/rembrandt#3]
As a representative of the Rembrandt platform, I'd like to showcase different use cases where the resource manager will be useful, for example in order to present them to the "customers" or to use them in explanations.

---

### :thought_balloon: Hints & Thoughts
- We already have the SMile use-case. Think about other areas where resources play an important role. (Medicine/hospital, other logistic domains, coffee machine access, ...)

### :question: Additional Questions to Answer / Consider
- For each new case, what is the important optimization/allocation, why is Rembrandt especially useful in that case, how do we outplay existing approaches?

---

## :white_check_mark: Conditions of satisfaction

- [x] Apart from SMile, at least two _additional_ use cases are found.
For each use case (including SMile):
- [x] The case is described, including the "problem" that needs to be solved.
- [x] The most important and necessary resources types are found and documented (including indispensable attributes)
- [x] Use case was discussed and accepted by the team.
~- [ ] Illustrative processes / fragments including resources and the "problem" are modeled.~

**Comment by Munin33** [comment]
the smile usecase is modeled in BPMN.io and stored in the drive
