### ISSUE TITLE
Prepare Presentation for Intermediate Presentation

### ISSUE THREAD

**Issue by MaximilianV** [bptlab/rembrandt#5]
As the development team, we'd like to have a well prepared presentation to guide the intermediate presentation.

---

## :white_check_mark: Conditions of satisfaction

- [ ] A presentation was created.
- [ ] The presentation follows the "Rembrandt" style.
- [ ] The outline and "unexpected" things from #4 are respected.
- [ ] The presentation was shown to the team and accepted.

**Comment by Munin33** [comment]
more things to prepare:
- “rocket”  visualization of the optimization UI
- Who uses when what? workflow for Rembrandt
- use cases BPMN models
- Resource life cycle (exemplary)
- Resource Type hierarchy (exemplary)
- Picture with 100 parcels and a desperate user
