### ISSUE TITLE
Start Wiki

### ISSUE THREAD

**Issue by MaximilianV** [bptlab/rembrandt#6]
As the development team, we'd like to document our decisions and the reasoning behind them in a simple and clear way.

---

### :thought_balloon: Hints & Thoughts
- The wiki should support the development part, as well as the research/decision part! (Why have we chosen to do this in this way?)
- Later, wiki entries should ease and support our process of writing the project paper.

---

## :white_check_mark: Conditions of satisfaction

- [x] A system for our wiki was chosen and presented to the team.
- [x] Every member is able to access / modify the wiki.
- [x] The usability of the wiki is good (easy to create new sites).
- [x] At least something like a "welcome" page exists.

**Comment by friedow** [comment]
As a wiki system we will use [GitBook](https://rembrandt.gitbook.io/docs/).
