### ISSUE TITLE
Make Appointment with Carla

### ISSUE THREAD

**Issue by MaximilianV** [bptlab/rembrandt#8]
As a developer, I'd like to have a deeper insight in optimization problems.

---

### :thought_balloon: Hints & Thoughts
- Carla is already working on an optimization component for the SMile use-case. Maybe we can draw inspiration from that.

---

## :white_check_mark: Conditions of satisfaction

- [x] An appointment with Carla was made.
- [x] Findings from the meeting are documented in the wiki.

**Comment by Munin33** [comment]
https://app.gitbook.com/@rembrandt/s/intern/meeting-with-carla
